[package]
name = "caw-orchestrator"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
caw-core = { path = "../caw-core" }
caw-transform = { path = "../caw-transform" }
regex = "1"

[dev-dependencies]
caw-adapters = { path = "../caw-adapters" }
caw-index = { path = "../caw-index" }
caw-ingest = { path = "../caw-ingest" }
tempfile = "3"
