[package]
name = "caw-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
caw-adapters = { workspace = true }
caw-core = { workspace = true }
caw-curation = { workspace = true }
caw-index = { workspace = true }
caw-ingest = { workspace = true }
caw-orchestrator = { workspace = true }
caw-transform = { workspace = true }
clap = { version = "4", features = ["derive"] }
